feign:
  httpclient:
    disable-ssl-validation: true
  hystrix:
    eneabled: true
  client:
    config:
      default:
        logger-level: basic
        read-timeout: 3000
        connect-timeout: 3000


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: validate
  flyway:
    locations: "classpath:db/migration"

management:
  endpoint:
    health:
      show-details: always

# TLS settings
server:
  ssl:
    enabled: true
    key-store-password: hunter2
    key-store: classpath:keystore/local-keystore.jks
    key-alias: localhost
    trust-store: classpath:keystore/local-truststore.jks
    trust-store-password: hunter2
    client-auth: need
  port: 8443
  http:
    port: 8080

logging:
  level:
    com:
      ezgroceries:
        shoppinglist: DEBUG
