create table COCKTAIL
(
    ID   UUID PRIMARY KEY,
    ID_DRINK TEXT,
    NAME TEXT,
    INGREDIENTS TEXT
);

CREATE TABLE COCKTAIL_SHOPPING_LIST (
    COCKTAIL_ID UUID REFERENCES COCKTAIL(ID),
    SHOPPING_LIST_ID UUID REFERENCES SHOPPING_LIST(ID),
    PRIMARY KEY(COCKTAIL_ID, SHOPPING_LIST_ID)
);